# Site settings
title: Coding in the basement
email: bringking@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Charles King's personal site and blog. A blog about software engineering, with a focus on front-end
  and mobile development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://charlesbking.com" # the base hostname & protocol for your site
twitter_username: thebringking
github_username:  bringking

# Build settings
markdown: kramdown
